### ISSUE TITLE
Issue while upgrading to ES 7.x with error="undefined method `host_unreachable_exceptions'

### ISSUE THREAD

**Issue by sunilkrg** [fluent/fluentd-kubernetes-daemonset#1303]
I changed the Gemfile and other configuration files referring to whatever is mentioned in this link(of fluentd-kubernetes-daemonset) - https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.11/debian-elasticsearch7

Now, I am below error which says host_unreachable. Although, I checked that the ES host is accessible from the Kubernetes environment

Deprecation notice: The elasticsearch-xpack gem will be deprecated and all the functionality will be available from elasticsearch-api.
See https://github.com/elastic/elasticsearch-ruby/issues/1274
2021-09-20 10:50:19 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `host_unreachable_exceptions' for #<Elasticsearch::Transport::Client:0x000055c0279cc6f0>"
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/elasticsearch_index_template.rb:41:in `rescue in retry_operate'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/elasticsearch_index_template.rb:39:in `retry_operate'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:1020:in `template_installation_actual'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/out_elasticsearch.rb:262:in `configure'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin.rb:173:in `configure'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/multi_output.rb:63:in `each'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/multi_output.rb:63:in `configure'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/out_copy.rb:38:in `configure'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin.rb:173:in `configure'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/agent.rb:132:in `add_match'
  2021-09-20 10:50:19 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.11.5/lib/fluent/agent.rb:74:in `block in configure'

I am finding it difficult to understand where is the actual issue, please help

**Comment by cosmo0920** [comment]
Already fixed in https://github.com/uken/fluent-plugin-elasticsearch/commit/d138d801ea5ade24e2d51a65378ad5f26a45954e and https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.14/debian-elasticsearch7.
