### ISSUE TITLE
v1.14.5 images are broken due to mismatched Ruby version

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [fluent/fluentd-kubernetes-daemonset#1336]
Hello, I'm currently investigating an issue with my kubernetes cluster. It appears that the latest build of `fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1` is failing to start up. according to kubernetes, the pod is crash looping with an exit code of 1. Nodes there are older than 3 hours old seem fine, and nodes that are younger than 3 hours seem to crash loop. I've included an example pod spec below, but there appears to be no logs, and the readme on dockerhub doesn't include any info how to enable debug level logs.

In the short term, I've temporarily changed my daemonset to target an older version by sha instead of using the tag.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-02-14T05:31:10Z"
  generateName: fluentd-
  labels:
    app: fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "1.0"
    controller-revision-hash: 54cff5888c
    helm.sh/chart: fluentd
    pod-template-generation: "4"
  name: fluentd-b8ncv
  namespace: common-logging
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: fluentd
    uid: cbc2b465-f073-4693-8199-c26a3c9e93a2
  resourceVersion: "1054909545"
  uid: 5b6ad221-e0f0-4492-8025-76374edeac66
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-10-128-101-237.us-west-2.compute.internal
  containers:
  - env:
    - name: FLUENT_ELASTICSEARCH_HOST
      value: elastic-common-es-http.common-logging.svc.cluster.local
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "9200"
    - name: FLUENT_ELASTICSEARCH_SCHEME
      value: https
    - name: FLUENT_UID
      value: "0"
    - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
      value: "false"
    - name: FLUENT_ELASTICSEARCH_SSL_VERSION
      value: TLSv1_2
    - name: FLUENT_ELASTICSEARCH_USER
      value: fluentd
    - name: FLUENT_ELASTICSEARCH_PASSWORD
      value: <secret>
    - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
      value: '[]'
    - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
      value: fluentd-default
    image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
    imagePullPolicy: IfNotPresent
    name: fluentd
    resources:
      limits:
        cpu: 500m
        memory: 750Mi
      requests:
        cpu: 500m
        memory: 750Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /fluentd/etc/conf.d
      name: fluentd-configuration
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fluentd-token-r4qg8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-128-101-237.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 1000000
  priorityClassName: high-priority
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fluentd
  serviceAccountName: fluentd
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      name: fluentd-configuration
    name: fluentd-configuration
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: varlibdockercontainers
  - name: fluentd-token-r4qg8
    secret:
      defaultMode: 420
      secretName: fluentd-token-r4qg8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    message: 'containers with unready status: [fluentd]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    message: 'containers with unready status: [fluentd]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://89007721aabaa5e14101685c803c2301cd6e2ebf776d70d37ba5ff1f8492ea37
    image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
    imageID: docker-pullable://fluent/fluentd-kubernetes-daemonset@sha256:ca6757a31e009bdab8334703970baf4b04430cfb2d72684af9a0dc3247d200fc
    lastState:
      terminated:
        containerID: docker://7640fd74ea4b8812f1b281be9df00a70573d9d09cb6ffa32bcad8b5cee86352e
        exitCode: 1
        finishedAt: "2022-02-14T05:41:51Z"
        reason: Error
        startedAt: "2022-02-14T05:41:51Z"
    name: fluentd
    ready: false
    restartCount: 8
    started: false
    state:
      terminated:
        containerID: docker://89007721aabaa5e14101685c803c2301cd6e2ebf776d70d37ba5ff1f8492ea37
        exitCode: 1
        finishedAt: "2022-02-14T05:47:01Z"
        reason: Error
        startedAt: "2022-02-14T05:47:00Z"
  hostIP: 10.128.101.237
  phase: Running
  podIP: 10.128.99.147
  podIPs:
  - ip: 10.128.99.147
  qosClass: Guaranteed
  startTime: "2022-02-14T05:31:10Z"
```

**Comment by xshyve** [comment]
We experience the same issue (we use the v1-debian-elasticsearch tag). It just reports an "exist code 1". Nothing more is visible. We have pinned the image to use an older tag now - with that it works for now.

**Comment by damienleger** [comment]
Same issue with `v1.14-debian-cloudwatch-1` (pushed Feb 14 2022 3:51AM). Problem fixed by rollback to previous tag `v1.14.3-debian-cloudwatch-1.0` (pushed Nov 13 2021 6:34AM).

**Comment by bryanasdev000** [comment]
Can confirm, no logs on stdout/stderr, just exit code 1, also rollback to `fluent/fluentd-kubernetes-daemonset:v1.14.3-debian-elasticsearch7-1.0` solved.

Running on EKS 1.20/1.21 (multiple clusters), with Elasticsearch 6.8 as target.

**Comment by HitkoDev** [comment]
Same for `fluent/fluentd-kubernetes-daemonset:v1.14-debian-forward-1`, and I believe the same problem exists in all `1.14.5` images.

**Comment by teqwve** [comment]
Same issue, fluentd is crash-looping with logs:
```
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluent-gem (Gem::GemNotFoundException)
    from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
    from /usr/local/bundle/bin/fluent-gem:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluent-gem (Gem::GemNotFoundException)
    from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
    from /usr/local/bundle/bin/fluent-gem:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluent-gem (Gem::GemNotFoundException)
    from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
    from /usr/local/bundle/bin/fluent-gem:23:in `<main>'
```

And indeed in new images `fluentd` gem package isn't installed (while it is installed in older images):
```
~ $ docker run --rm -t -i --entrypoint /bin/bash fluent/fluentd-kubernetes-daemonset:v1.14.3-debian-elasticsearch6-amd64-1.0 -c "gem list | grep fluentd"
fluentd (1.14.3)
~ $ docker run --rm -t -i --entrypoint /bin/bash fluent/fluentd-kubernetes-daemonset:v1.14.5-debian-elasticsearch6-amd64-1.0 -c "gem list | grep fluentd"
~ $
```

**Comment by teqwve** [comment]
With 1.14.5 release there was a ruby version upgrade in official / upstream image - https://github.com/fluent/fluentd-docker-image/commit/bded5adfdbc9b31fc156d404c023fb3b5e48b499#diff-ab84b5cc90eb1947bd84eeedd885746d625c110ef75a0a02dee3d52d9f46af4a - while ruby version that is [in various paths in Dockerfile](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/templates/Dockerfile.erb#L25) wasn't updated. I guess that the fix would be to replace `2.6.0` by `2.7.0` in this Dockerfile.

![2022-02-14-204402_802x325_scrot](https://user-images.githubusercontent.com/6898749/153935011-dbb80e7a-4e86-47d4-ac49-32f51696e0d5.png)

**Comment by ashie** [comment]
I keep this opened until images are released.

**Comment by kenhys** [comment]
It requires one more PR to fix.

**Comment by kenhys** [comment]
I've created another PR to fix it #1340

**Comment by kenhys** [comment]
Now building new images...

**Comment by kenhys** [comment]
New images were published.
