### ISSUE TITLE
fluentd-kubernetes-daemonset with alpine-graylog crashes on startup

### ISSUE THREAD

**Issue by astmuc** [fluent/fluentd-kubernetes-daemonset#134]
After closing the match section in docker-image/v0.12/alpine-graylog/conf/fluent.conf i created a image and applied a yaml based on fluentd-daemonset-papertrail.yaml. The pod loads but crashes directly after start with

`2018-05-11 14:03:26 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2018-05-11 14:03:26 +0000 [info]: starting fluentd-0.12.33
2018-05-11 14:03:26 +0000 [info]: gem 'fluent-plugin-gelf-hs' version '1.0.6'
2018-05-11 14:03:26 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '1.0.2'
2018-05-11 14:03:26 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
2018-05-11 14:03:26 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2018-05-11 14:03:26 +0000 [info]: gem 'fluentd' version '0.12.33'
2018-05-11 14:03:26 +0000 [info]: adding match pattern="fluent.**" type="null"
2018-05-11 14:03:26 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2018-05-11 14:03:27 +0000 [info]: adding match pattern="**" type="gelf"
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gelf (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-gelf-hs-1.0.6/lib/fluent/plugin/out_gelf.rb:11:in `<class:GELFOutput>'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-gelf-hs-1.0.6/lib/fluent/plugin/out_gelf.rb:3:in `<module:Fluent>'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-gelf-hs-1.0.6/lib/fluent/plugin/out_gelf.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.33/lib/fluent/plugin.rb:172:in `block in try_load_plugin'`

I did not change anything else than the fluent.conf.

**Comment by adamp524** [comment]
I'm facing the same problem today. Have been looking into it too but I'm not very familiar with Ruby.

**Comment by tchelovilar** [comment]
Hi,

I fix this in #144
