### ISSUE TITLE
OpenSearch Image crashing on startup

### ISSUE THREAD

**Issue by PascalTurbo** [fluent/fluentd-kubernetes-daemonset#1374]
When using the current opensearch image `fluent/fluentd-kubernetes-daemonset:v1.15.0-debian-opensearch-1.0` fluentd pod crashes on startup with the following error:

```
/fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml/parser.rb:74:in `set_default_engine': Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml (RuntimeError)
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml/parser.rb:96:in `<class:Parser>'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml/parser.rb:7:in `<module:Xml>'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml/parser.rb:5:in `<module:Aws>'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml/parser.rb:3:in `<top (required)>'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml.rb:8:in `require_relative'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml.rb:8:in `<top (required)>'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core.rb:68:in `require_relative'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core.rb:68:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:57:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.0/lib/fluent/registry.rb:103:in `block in search'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.0/lib/fluent/registry.rb:100:in `each'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.0/lib/fluent/registry.rb:100:in `search'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.0/lib/fluent/registry.rb:44:in `lookup'
	from /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.0/lib/fluent/plugin.rb:169:in `new_impl'
```

**Comment by ashie** [comment]
Ah sorry, current image lacks rexml gem because Ruby 3.x drop it from default gem.
I'll add it.
