### ISSUE TITLE
Access denied to /var/log unless FLUENT_UID is set to 0

### ISSUE THREAD

**Issue by rajarajanpsj** [fluent/fluentd-kubernetes-daemonset#173]
When I deployed fluent/fluentd-kubernetes-daemonset:v0.12.43-debian-cloudwatch to an EKS cluster, I was constantly getting access denied errors in /var/log. It was resolved when FLUENT_UID environment variable is set to 0. In the DockerFile i do see that USER is set to ROOT and when I exec into the daemonset pod,  I am able to create/read files in /var/log but however the fluentd process (or the child process?) is not able to create files under /var/log UNLESS I set this environment variable FLUENT_UID to "0". If this is required, should it not be default? what is the significance of this environment variable?

**Comment by repeatedly** [comment]
This is same with https://github.com/fluent/fluentd-kubernetes-daemonset/issues/172 .
We update base image and it seems to cause permission error.
if setting FLUENT_UID to 0 in Dockerfile resolve the problem, we should do it.

**Comment by vpistis** [comment]
same problem, solved with `USER root` and `ENV FLUENT_UID 0`

**Comment by PierrickI3** [comment]
Setting the env var FLUENT_UID to "0" fixed it for me too

**Comment by buchmui** [comment]
```      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        securityContext:
          runAsUser: 0
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.logging.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: "FLUENT_UID"
            value: "0"
        resources:
```

**Comment by dimm0** [comment]
FLUENT_UID is not helping...

**Comment by mbolek** [comment]
@dimm0 any additional info? This seems to work for me but by breaking not working around the issue :)

**Comment by dimm0** [comment]
I'm hitting this error https://github.com/fluent/fluentd-kubernetes-daemonset/issues/172, pods are crashlooping, setting FLUENT_UID to 0 is not helping, running pod as user 0 is not helping either. Not sure what other info to provide

**Comment by dimm0** [comment]
Here's my yaml: https://gitlab.com/ucsd-prp/prp_k8s_config/blob/master/fluentd/fluentd-daemonset-elasticsearch.yaml

I saw a PR with pos_file, which was denied. And there's no such setting in examples. What should I set one to?

**Comment by mbolek** [comment]
@dimm0 I think you are using the image from #180 (which is fluentd-0.12.33) that doesn't need the FLUENT_UID workaround as the fluentd in the container is running as root.
FLUENT_UID workaround is meant for the latest image i.e. fluent/fluentd-kubernetes-daemonset:v1.2.2-debian-elasticsearch so you could try running latest image with this variable set to 0

**Comment by dimm0** [comment]
```
2018-09-19 17:31:51 +0000 [error]: unexpected error error_class=Errno::EACCES error=#<Errno::EACCES: Permission denied @ rb_sysopen - /var/log/fluentd-containers.log.pos>
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_tail.rb:145:in `initialize'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_tail.rb:145:in `open'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_tail.rb:145:in `start'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/root_agent.rb:115:in `block in start'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/root_agent.rb:114:in `each'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/root_agent.rb:114:in `start'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/engine.rb:237:in `start'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/engine.rb:187:in `run'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:570:in `run_engine'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:162:in `block in start'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:366:in `main_process'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:339:in `block in supervise'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:338:in `fork'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:338:in `supervise'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:156:in `start'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2018-09-19 17:31:51 +0000 [error]: /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-09-19 17:31:51 +0000 [error]: /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/bin/fluentd:8:in `<top (required)>'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/bin/fluentd:23:in `load'
  2018-09-19 17:31:51 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/bin/fluentd:23:in `<main>'
2018-09-19 17:31:51 +0000 [info]: shutting down fluentd
2018-09-19 17:31:51 +0000 [info]: shutting down filter type="kubernetes_metadata" plugin_id="filter_kube_metadata"
2018-09-19 17:31:51 +0000 [info]: shutting down output type="elasticsearch" plugin_id="out_es"
2018-09-19 17:31:51 +0000 [info]: shutting down output type="null" plugin_id="object:2ad702842034"
2018-09-19 17:31:51 +0000 [info]: process finished code=0
2018-09-19 17:31:51 +0000 [warn]: process died within 1 second. exit.
```

image: fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch

```
          - name: FLUENT_UID
            value: "0"
```

**Comment by dimm0** [comment]
Solved by adding `imagePullPolicy: Always`. It was using the old image

**Comment by vigohe** [comment]
same issue with v0.12-debian-elasticsearch `FLUENT_UID` to 0 did fix it
