### ISSUE TITLE
[error]: [in_systemd_kubelet] Exception emitting record: undefined method `emit' for nil:NilClass

### ISSUE THREAD

**Issue by AjeetK** [fluent/fluentd-kubernetes-daemonset#192]
I am trying out `debian-elasticsearch` with version `1.2`. The `fluent.conf`, `systemd.conf` and `kubernetes.conf` remains the default one.

**Expectation** - All kubernetes logs in Elasticsearch-kibana with prefix `logstash`
**Issue** - Logs appear in elasticsearch for a while and then pods gets terminated with the following error:

```
fluentd-zgkkf fluentd 2018-09-08 23:47:32 +0000 [error]: [in_systemd_kubelet] Exception emitting record: undefined method `emit' for nil:NilClass
fluentd-zgkkf fluentd Did you mean?  exit
fluentd-zgkkf fluentd 2018-09-08 23:47:33 +0000 [error]: [in_systemd_kubelet] Exception emitting record: undefined method `emit' for nil:NilClass
fluentd-zgkkf fluentd Did you mean?  exit
fluentd-zgkkf fluentd 2018-09-08 23:47:33 +0000 [error]: [in_systemd_kubelet] Exception emitting record: undefined method `emit' for nil:NilClass
fluentd-zgkkf fluentd Did you mean?  exit
fluentd-zgkkf fluentd 2018-09-08 23:47:33 +0000 [error]: [in_systemd_kubelet] Exception emitting record: undefined method `emit' for nil:NilClass
fluentd-zgkkf fluentd Did you mean?  exit
fluentd-zgkkf fluentd 2018-09-08 23:47:33 +0000 [warn]: [in_systemd_kubelet] killing existing thread thread=#<Thread:0x007f81a3586b88@/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin_helper/thread.rb:70 sleep>
fluentd-zgkkf fluentd 2018-09-08 23:47:33 +0000 [warn]: [in_systemd_kubelet] thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::SystemdInput title=:event_loop thread=#<Thread:0x007f81a3586b88@/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.5/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
```

Found a similar issue [here](https://github.com/reevoo/fluent-plugin-systemd/issues/46 )
Seems like some version issue with the Gems getting installed.

**Comment by cristifalcas** [comment]
Have the same problem wit latest fluentd.

Multiple exception on SIGHUP:
```
2018-11-23 10:39:50 +0000 [error]: unexpected error error_class=SignalException error="SIGHUP"
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/engine.rb:228:in `sleep'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/engine.rb:228:in `run'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:799:in `run_engine'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:724:in `main_process'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:544:in `run_worker'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-11-23 10:39:50 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-11-23 10:39:50 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-11-23 10:39:50 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/bin/fluentd:8:in `<top (required)>'
  2018-11-23 10:39:50 +0000 [error]: /usr/local/bin/fluentd:22:in `load'
  2018-11-23 10:39:50 +0000 [error]: /usr/local/bin/fluentd:22:in `<main>'
2018-11-23 10:39:50 +0000 [warn]: [systemd-input] thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::SystemdInput title=:event_loop thread=#<Thread:0x007fcdc9712660@/var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2018-11-23 10:39:50 +0000 [warn]: thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::PrometheusInput title=:in_prometheus thread=#<Thread:0x007fcdc97129d0@/var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
```

And this:
```
2018-11-23 10:35:53 +0000 [error]: unexpected error error_class=SignalException error="SIGHUP"
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/engine.rb:228:in `sleep'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/engine.rb:228:in `run'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:799:in `run_engine'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:724:in `main_process'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:544:in `run_worker'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-11-23 10:35:53 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-11-23 10:35:53 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-11-23 10:35:53 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.3.0/bin/fluentd:8:in `<top (required)>'
  2018-11-23 10:35:53 +0000 [error]: /usr/local/bin/fluentd:22:in `load'
  2018-11-23 10:35:53 +0000 [error]: /usr/local/bin/fluentd:22:in `<main>'
2018-11-23 10:35:53 +0000 [warn]: [elasticsearch] thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutput title=:enqueue_thread thread=#<Thread:0x007fa240f20820@/var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2018-11-23 10:35:53 +0000 [warn]: [elasticsearch] thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_1 thread=#<Thread:0x007fa240f20bb8@/var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
```

**Comment by AjeetK** [comment]
@cristifalcas In which namespace are you trying to run fluentd-daemonset? In my case, I am running K8s on GKE and when I was running fluentd-daemonset in `kube-system` namespace, I was getting these errors. Now I have switched to `default` namespace and everything is working fine.
