### ISSUE TITLE
 Whether different images depend on the version of k8s？

### ISSUE THREAD

**Issue by langzi-zmg** [fluent/fluentd-kubernetes-daemonset#212]
test env: the version of k8s is 1.10.5
prod env: the version of k8s is 1.7.8

the image of fluentd-kubernetes-daemonset  is   v1.2/debian-kafka
test env is ok,but prod env is not ok.
prod env error message:
Send exception occurred: Failed to send messages to applog2kafka/0

**Comment by langzi-zmg** [comment]
please help me

**Comment by langzi-zmg** [comment]
@erhudy

**Comment by langzi-zmg** [comment]
{"log":"2018-10-24 09:16:54 +0000 [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2018-10-24 09:21:15 +0000 chunk=\"578f5ea1ef09046eeda531d9420fbddc\" error_class=Kafka::DeliveryFailed error=\"Failed to send messages to applog2kafka4gray/0, applog2kafka4gray/1\"\n","stream":"stdout","time":"2018-10-24T09:16:54.423733325Z"}
{"log":"  2018-10-24 09:16:54 +0000 [warn]: #0 suppressed same stacktrace\n","stream":"stdout","time":"2018-10-24T09:16:54.423736734Z"}
{"log":"2018-10-24 09:16:54 +0000 [debug]: #0 Sending produce API request 1 to 10.1.0.30:9092\n","stream":"stdout","time":"2018-10-24T09:16:54.423739365Z"}
{"log":"2018-10-24 09:16:54 +0000 [debug]: #0 Waiting for response 1 from 10.1.0.30:9092\n","stream":"stdout","time":"2018-10-24T09:16:54.423742179Z"}
{"log":"2018-10-24 09:16:54 +0000 [debug]: #0 Received response 1 from 10.1.0.30:9092\n","stream":"stdout","time":"2018-10-24T09:16:54.427292656Z"}
{"log":"2018-10-24 09:16:54 +0000 [error]: #0 Timed out while writing to applog2kafka4gray/2 on 10.1.0.30:9092 (node_id=11)\n","stream":"stdout","time":"2018-10-24T09:16:54.427312343Z"}
{"log":"2018-10-24 09:16:54 +0000 [error]: #0 Failed to send all messages; keeping remaining messages in buffer\n","stream":"stdout","time":"2018-10-24T09:16:54.427318236Z"}
{"log":"2018-10-24 09:16:54 +0000 [warn]: #0 Send exception occurred: Failed to send messages to applog2kafka4gray/1, applog2kafka4gray/2\n","stream":"stdout","time":"2018-10-24T09:16:54.427322732Z"}
{"log":"2018-10-24 09:16:54 +0000 [warn]: #0 Exception Backtrace : /fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:330:in `deliver_messages_with_retries'\n","stream":"stdout","time":"2018-10-24T09:16:54.427328004Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:238:in `block in deliver_messages'\n","stream":"stdout","time":"2018-10-24T09:16:54.427333292Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'\n","stream":"stdout","time":"2018-10-24T09:16:54.427337184Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/instrumenter.rb:21:in `instrument'\n","stream":"stdout","time":"2018-10-24T09:16:54.427341386Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:231:in `deliver_messages'\n","stream":"stdout","time":"2018-10-24T09:16:54.427345526Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:281:in `deliver_messages'\n","stream":"stdout","time":"2018-10-24T09:16:54.427349564Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:330:in `block in write'\n","stream":"stdout","time":"2018-10-24T09:16:54.427353715Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/event.rb:323:in `each'\n","stream":"stdout","time":"2018-10-24T09:16:54.427357818Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/event.rb:323:in `block in each'\n","stream":"stdout","time":"2018-10-24T09:16:54.427362005Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'\n","stream":"stdout","time":"2018-10-24T09:16:54.427366381Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'\n","stream":"stdout","time":"2018-10-24T09:16:54.42737061Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/event.rb:322:in `each'\n","stream":"stdout","time":"2018-10-24T09:16:54.427374611Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:298:in `write'\n","stream":"stdout","time":"2018-10-24T09:16:54.427386772Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/compat/output.rb:131:in `write'\n","stream":"stdout","time":"2018-10-24T09:16:54.427397952Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:1111:in `try_flush'\n","stream":"stdout","time":"2018-10-24T09:16:54.427403482Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:1394:in `flush_thread_run'\n","stream":"stdout","time":"2018-10-24T09:16:54.427407637Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:445:in `block (2 levels) in start'\n","stream":"stdout","time":"2018-10-24T09:16:54.427411746Z"}
{"log":"/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'\n","stream":"stdout","time":"2018-10-24T09:16:54.427415551Z"}
