### ISSUE TITLE
v1.2 debian-logentries issues with SSL

### ISSUE THREAD

**Issue by nitin302** [fluent/fluentd-kubernetes-daemonset#241]
Seeing the below errors. Tailing container logs works for sometime, then shows up these errors.

  2018-12-11 08:05:50 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:1394:in `flush_thread_run'
  2018-12-11 08:05:50 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:445:in `block (2 levels) in start'
  2018-12-11 08:05:50 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-12-11 08:05:51 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-11 08:05:51 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:05:51 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:05:52 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=1 next_retry_seconds=2018-12-11 08:05:52 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:05:52 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:05:54 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=2 next_retry_seconds=2018-12-11 08:05:54 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:05:54 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:05:58 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=3 next_retry_seconds=2018-12-11 08:05:58 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:05:58 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:06:06 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=4 next_retry_seconds=2018-12-11 08:06:06 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:06:06 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:06:16 +0000 [info]: #0 [in_tail_container_logs] following tail of /var/log/containers/k8s-admin-worker-9765966c9-5f2pj_default_k8s-admin-worker-2e44862ecd178a14531ee3aa501cf51c9ac78ad045efbe0e3193e4122354010d.log
2018-12-11 08:06:16 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 1, pod_cache_size: 3, namespace_cache_api_updates: 4, pod_cache_api_updates: 4, id_cache_miss: 4, pod_cache_watch_updates: 12, pod_cache_watch_misses: 10, pod_cache_watch_delete_ignored: 2, pod_cache_watch_ignored: 2
2018-12-11 08:06:24 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=5 next_retry_seconds=2018-12-11 08:06:24 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:06:24 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:06:53 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=6 next_retry_seconds=2018-12-11 08:06:53 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:06:53 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:06:57 +0000 [info]: #0 [in_tail_container_logs] detected rotation of /var/log/containers/k8s-admin-worker-9765966c9-5f2pj_default_k8s-admin-worker-2e44862ecd178a14531ee3aa501cf51c9ac78ad045efbe0e3193e4122354010d.log; waiting 5 seconds
2018-12-11 08:07:16 +0000 [info]: #0 [in_tail_container_logs] following tail of /var/log/containers/k8s-admin-worker-9765966c9-mgcph_default_k8s-admin-worker-8c57a2a8f95b4d1686fe844efb512e0cc874ee0bc4a08978b01133c0b7afb213.log
2018-12-11 08:07:16 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 1, pod_cache_size: 4, namespace_cache_api_updates: 5, pod_cache_api_updates: 5, id_cache_miss: 5, pod_cache_watch_delete_ignored: 3, pod_cache_watch_updates: 13, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 3
2018-12-11 08:07:50 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=7 next_retry_seconds=2018-12-11 08:07:50 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:07:50 +0000 [warn]: #0 suppressed same stacktrace
2018-12-11 08:10:00 +0000 [warn]: #0 [out_logentries] failed to flush the buffer. retry_time=8 next_retry_seconds=2018-12-11 08:10:00 +0000 chunk="57cba8901083756904f6b6b5d16654b5" error_class=OpenSSL::SSL::SSLError error="SSL_write: bad write retry"
  2018-12-11 08:10:00 +0000 [warn]: #0 suppressed same stacktrace

**Comment by moleskin-smile** [comment]
@repeatedly: in order to close this, #289 should be merged first. Can we please reopen?

(This issue was closed automatically due to my usage of the "fixes" keyword).
