### ISSUE TITLE
#0 [in_systemd_kubelet] Systemd::JournalError: No such file fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch

### ISSUE THREAD

**Issue by eskuai** [fluent/fluentd-kubernetes-daemonset#274]
fluentd
Image:
fluent/fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch
Environment variables:
FLUENT_ELASTICSEARCH_HOST: elasticsearch-logging
FLUENT_ELASTICSEARCH_PORT: 9200
FLUENT_ELASTICSEARCH_SCHEME: http
FLUENT_ELASTICSEARCH_USER: elastic
FLUENT_ELASTICSEARCH_PASSWORD: changeme
FLUENT_UID: 0
FLUENTD_SYSTEMD_CONF: disable
FLUENT_ELASTICSEARCH_SED_DISABLE: true
TZ: Europe/Madrid
Commands:

I got the same problems,
019-02-27 10:54:42 +0100 [warn]: #0 [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:42 +0100 [warn]: #0 [in_systemd_kubelet] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:43 +0100 [warn]: #0 [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:43 +0100 [warn]: #0 [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:43 +0100 [warn]: #0 [in_systemd_kubelet] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:44 +0100 [warn]: #0 [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:44 +0100 [warn]: #0 [in_systemd_kubelet] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:44 +0100 [warn]: #0 [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:45 +0100 [warn]: #0 [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:45 +0100 [warn]: #0 [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:45 +0100 [warn]: #0 [in_systemd_kubelet] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:46 +0100 [warn]: #0 [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 10:54:46 +0100 [warn]: #0 [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s

**Comment by zerthimon** [comment]
@eskuai take a look at this https://github.com/reevoo/fluent-plugin-systemd#how-can-i-use-this-plugin-inside-of-a-docker-container-
You need to add a host volume to a `/var/log/journal`

**Comment by eskuai** [comment]
can you help me?

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogjournal
        hostPath:
          path: /var/log/journal                       
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: fluentd-config

is it ok?

but it is no working :;(

**Comment by eskuai** [comment]
2019-02-28 17:05:44 +0100 [info]: starting fluentd-1.3.2 pid=6 ruby="2.3.3"
2019-02-28 17:05:44 +0100 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.6/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:34:in `rescue in start_pod_watch': Exception encountered fetching metadata from Kubernetes API endpoint: pods is forbidden: User "system:serviceaccount:kube-system:fluentd" cannot list resource "pods" in API group "" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "fluentd" not found ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:kube-system:fluentd\" cannot list resource \"pods\" in API group \"\" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io \"fluentd\" not found","reason":"Forbidden","details":{"kind":"pods"},"code":403} (Fluent::ConfigError)
)
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.6/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:27:in `start_pod_watch'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:260:in `block in configure'

**Comment by zerthimon** [comment]
You should using a manifest with `-rbac` prefix:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch-rbac.yaml
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-cloudwatch-rbac.yaml
... Or copy the `.rbac` entries from those files and apply them into k8s.

**Comment by ForbesLindesay** [comment]
I'm getting the same problem and I'm using the rbac version as @zerthimon suggests

**Comment by ForbesLindesay** [comment]
This was resolved by https://github.com/fluent/fluentd-kubernetes-daemonset#disable-systemd-input for me

**Comment by cosmo0920** [comment]
Mounting `/var/log/journal` or setting `"disable"` to `FLUENTD_SYSTEMD_CONF` should solve this issue.
Closing.
