### ISSUE TITLE
temporarily failed to flush the buffer

### ISSUE THREAD

**Issue by typ431127** [fluent/fluentd-kubernetes-daemonset#304]
My fluentd has been reporting an error
docker version: 17.03.2-ce
kubernetes version:  v1.12.1
fluentd image: fluent/fluentd-kubernetes-daemonset:elasticsearch
### yml file
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "192.168.100.195"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_UID
            value: "0"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
          - name: FLUENTD_PROMETHEUS_CONF
            value: "disable"
          # Option to configure elasticsearch plugin with self signed certs
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          # X-Pack Authentication
          # =====================
          - name: FLUENT_ELASTICSEARCH_USER
            value: ""
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: ""
          # Logz.io Authentication
          # ======================
          - name: LOGZIO_TOKEN
            value: "ThisIsASuperLongToken"
          - name: LOGZIO_LOGTYPE
            value: "kubernetes"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```
### error
> [root@node3 ~]# docker logs 02562402c864
adduser: uid '0' in use
chown: unknown user fluent
chown: unknown user fluent
2019-04-22 06:20:56 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2019-04-22 06:20:56 +0000 [info]: starting fluentd-0.12.43
2019-04-22 06:20:57 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.18.0'
2019-04-22 06:20:57 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '1.2.1'
2019-04-22 06:20:57 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
2019-04-22 06:20:57 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.6.0'
2019-04-22 06:20:57 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2019-04-22 06:20:57 +0000 [info]: gem 'fluentd' version '0.12.43'
2019-04-22 06:20:57 +0000 [info]: adding match pattern="fluent.**" type="null"
2019-04-22 06:20:57 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2019-04-22 06:20:58 +0000 [info]: adding match pattern="**" type="elasticsearch"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: adding source type="tail"
2019-04-22 06:20:58 +0000 [info]: using configuration file: <ROOT>
  <match fluent.**>
    @type null
  </match>
  <source>
    @type tail
    @id in_tail_container_logs
    path /var/log/containers/*.log
    pos_file /var/log/fluentd-containers.log.pos
    tag kubernetes.*
    read_from_head true
    format json
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </source>
  <source>
    @type tail
    @id in_tail_minion
    path /var/log/salt/minion
    pos_file /var/log/fluentd-salt.pos
    tag salt
    format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
    time_format %Y-%m-%d %H:%M:%S
  </source>
  <source>
    @type tail
    @id in_tail_startupscript
    path /var/log/startupscript.log
    pos_file /var/log/fluentd-startupscript.log.pos
    tag startupscript
    format syslog
  </source>
  <source>
    @type tail
    @id in_tail_docker
    path /var/log/docker.log
    pos_file /var/log/fluentd-docker.log.pos
    tag docker
    format /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
  </source>
  <source>
    @type tail
    @id in_tail_etcd
    path /var/log/etcd.log
    pos_file /var/log/fluentd-etcd.log.pos
    tag etcd
    format none
  </source>
  <source>
    @type tail
    @id in_tail_kubelet
    multiline_flush_interval 5s
    path /var/log/kubelet.log
    pos_file /var/log/fluentd-kubelet.log.pos
    tag kubelet
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_kube_proxy
    multiline_flush_interval 5s
    path /var/log/kube-proxy.log
    pos_file /var/log/fluentd-kube-proxy.log.pos
    tag kube-proxy
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_kube_apiserver
    multiline_flush_interval 5s
    path /var/log/kube-apiserver.log
    pos_file /var/log/fluentd-kube-apiserver.log.pos
    tag kube-apiserver
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_kube_controller_manager
    multiline_flush_interval 5s
    path /var/log/kube-controller-manager.log
    pos_file /var/log/fluentd-kube-controller-manager.log.pos
    tag kube-controller-manager
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_kube_scheduler
    multiline_flush_interval 5s
    path /var/log/kube-scheduler.log
    pos_file /var/log/fluentd-kube-scheduler.log.pos
    tag kube-scheduler
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_rescheduler
    multiline_flush_interval 5s
    path /var/log/rescheduler.log
    pos_file /var/log/fluentd-rescheduler.log.pos
    tag rescheduler
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_glbc
    multiline_flush_interval 5s
    path /var/log/glbc.log
    pos_file /var/log/fluentd-glbc.log.pos
    tag glbc
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_cluster_autoscaler
    multiline_flush_interval 5s
    path /var/log/cluster-autoscaler.log
    pos_file /var/log/fluentd-cluster-autoscaler.log.pos
    tag cluster-autoscaler
    format kubernetes
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </source>
  <source>
    @type tail
    @id in_tail_kube_apiserver_audit
    multiline_flush_interval 5s
    path /var/log/kubernetes/kube-apiserver-audit.log
    pos_file /var/log/kube-apiserver-audit.log.pos
    tag kube-apiserver-audit
    format multiline
    format_firstline /^\S+\s+AUDIT:/
    format1 /^(?<time>\S+) AUDIT:(?: (?:id="(?<id>(?:[^"\\]|\\.)*)"|ip="(?<ip>(?:[^"\\]|\\.)*)"|method="(?<method>(?:[^"\\]|\\.)*)"|user="(?<user>(?:[^"\\]|\\.)*)"|groups="(?<groups>(?:[^"\\]|\\.)*)"|as="(?<as>(?:[^"\\]|\\.)*)"|asgroups="(?<asgroups>(?:[^"\\]|\\.)*)"|namespace="(?<namespace>(?:[^"\\]|\\.)*)"|uri="(?<uri>(?:[^"\\]|\\.)*)"|response="(?<response>(?:[^"\\]|\\.)*)"|\w+="(?:[^"\\]|\\.)*"))*/
    time_format %FT%T.%L%Z
  </source>
  <filter kubernetes.**>
    @type kubernetes_metadata
    @id filter_kube_metadata
  </filter>
  <match **>
    @type elasticsearch
    @id out_es
    @log_level info
    include_tag_key true
    host 192.168.100.195
    port 9200
    scheme http
    ssl_verify false
    reload_connections true
    logstash_prefix logstash
    logstash_format true
    type_name fluentd
    buffer_chunk_limit 2M
    buffer_queue_limit 32
    flush_interval 5s
    max_retry_wait 30
    disable_retry_limit 
    num_threads 8
  </match>
</ROOT>
2019-04-22 06:20:58 +0000 [info]: following tail of /var/log/containers/kube-proxy-grmjx_kube-system_kube-proxy-14799cbb52383f1c94b92e316fe3137571b82b5a1c605a37743f81067cf48076.log
2019-04-22 06:20:58 +0000 [info]: following tail of /var/log/containers/kube-flannel-ds-8dkrp_kube-system_kube-flannel-3bc8bee0362f14764642515feb14232749c3ef1924d6e40a1c94125adb867f4c.log
2019-04-22 06:20:58 +0000 [info]: following tail of /var/log/containers/kube-flannel-ds-8dkrp_kube-system_install-cni-51bd0c3da96b9c34eed568616272ff0d698f958bf9148e1ecc06d0116d74fb1b.log
2019-04-22 06:20:58 +0000 [info]: following tail of /var/log/containers/kube-flannel-ds-8dkrp_kube-system_kube-flannel-9efee35a07f3c76a2157aebff9fb4b075e9ecf598c2d7f01a141d14c8712175f.log
2019-04-22 06:20:58 +0000 [info]: following tail of /var/log/containers/kube-proxy-grmjx_kube-system_kube-proxy-c39f37c51ca1f01bcfd65bf79beaba2f66cc7fe8b45e0c069b3657ce693d1a61.log
2019-04-22 06:20:58 +0000 [info]: following tail of /var/log/containers/fluentd-c8mm4_kube-system_fluentd-02562402c8642459ea5d4132079d412465180e22a5c8275c1275a337eea7f81d.log
2019-04-22 06:21:04 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"192.168.100.195", :port=>9200, :scheme=>"http"}
2019-04-22 06:21:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:21:05 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/oj-3.5.1/lib/oj/mimic.rb:2:in `<top (required)>'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/oj-3.5.1/lib/oj.rb:17:in `<top (required)>'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json/adapters/oj.rb:2:in `<top (required)>'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:157:in `load_adapter_from_string_name'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:101:in `load_adapter'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:103:in `load_adapter'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:91:in `use'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:73:in `adapter'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:133:in `current_adapter'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:120:in `load'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:24:in `load'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:326:in `perform_request'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/elasticsearch-api-6.1.0/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-elasticsearch-1.18.0/lib/fluent/plugin/out_elasticsearch.rb:467:in `send_bulk'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-elasticsearch-1.18.0/lib/fluent/plugin/out_elasticsearch.rb:382:in `write_objects'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:490:in `write'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:354:in `write_chunk'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:333:in `pop'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:342:in `try_flush'
  2019-04-22 06:21:04 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:149:in `run'
2019-04-22 06:21:05 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:21:07 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:21:05 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:21:07 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:21:11 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:21:07 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:21:11 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:21:19 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:21:11 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:21:19 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:21:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:21:19 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:21:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:22:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:21:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:21:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:22:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:22:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:22:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:22:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:22:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:23:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:22:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:22:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:23:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:23:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:23:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:23:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:23:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:24:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:23:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:23:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:24:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:24:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:24:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:24:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:24:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:25:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:24:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:24:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:25:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:25:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:25:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:25:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:25:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:26:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:25:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:25:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:26:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:26:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:26:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:26:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:26:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:27:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:26:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:26:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:27:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:27:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:27:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:27:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:27:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:28:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:27:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:27:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:28:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:28:34 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:28:04 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:28:05 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1
2019-04-22 06:28:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-22 06:29:04 +0000 error_class="MultiJson::AdapterError" error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)." plugin_id="out_es"
  2019-04-22 06:28:34 +0000 [warn]: suppressed same stacktrace
2019-04-22 06:28:35 +0000 [info]: stats - namespace_cache_size: 1, pod_cache_size: 1, namespace_cache_api_updates: 1, pod_cache_api_updates: 1, id_cache_miss: 1

**Comment by Madhansudhan** [comment]
Hi,
Am also facing the issue similar to the above. Wanna to understand where the user fluent configured. And how the container states the UID is already in use.

Thanks.
