### ISSUE TITLE
Failure: namespaces is forbidden

### ISSUE THREAD

**Issue by collimarco** [fluent/fluentd-kubernetes-daemonset#321]
I have tried this file on a new DigitalOcean K8s cluster:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml

I am using Loz.io and I have configured all the env variables properly.

The problem is that the container crashes and these are the pod logs:

```
#<Thread:0x000055807f5a0d48@/fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-1.2.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:234 run> terminated with exception (report_on_exception is true):
/fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-1.2.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:34:in `rescue in start_namespace_watch': start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.245.0.1:443/api: namespaces is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "namespaces" in API group "" at the cluster scope ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"namespaces"},"code":403} (Fluent::ConfigError)
)
	from /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-1.2.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:27:in `start_namespace_watch'
	from /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-1.2.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:234:in `block in configure'
```

**Comment by mosfet1kg** [comment]
I'm also stuck in this problem.

I thinks we need to grant permission to fluentd in order to make them see k8s meta info.

First of all, make cluster a role and then set `serviceAccount` info to daemonset.

refer to the following link

https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/daemonset/rbac/fluentd.yaml
