### ISSUE TITLE
Parsing PHP Stack Trace

### ISSUE THREAD

**Issue by arunv707** [fluent/fluentd-kubernetes-daemonset#337]
Hello,

I have an issue while parsing PHP Stack Trace. Currently I want to parse the following logs from my Kubernetes pod.
```
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: "EXCPT_START: /var/www/core/Redis.php:61  Redis connection failed php_network_getaddresses: getaddrinfo failed: Name d"es not resolve
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: " #0 /var/www/core/Redis.php(39): admin\core\Redis->connect(NULL, '6379', '0', '2.5')"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: "#1 /var/www/core/Container.php(93): admin\core\Redis->__construct(Array)"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: "#2 /var/www/core/Container.php(115): admin\core\Container::admin\core\{closure}()"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: "#3 /var/www/models/Dashboard.php(334): admin\core\Container::getService('redisReader')"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: "#4 /var/www/controllers/Dashboard.php(139): admin\models\Dashboard->getLoggedUserCount()"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: "#5 /var/www/index.php(49): admin\controllers\Dashboard->onlineUsersCount(Array)"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 114 said into stdout: " EXCPT_END"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "WARN_START: /var/www/core/Redis.php:57  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve WARN_END"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "EXCPT_START: /var/www/core/Redis.php:61  Redis connection failed php_network_getaddresses: getaddrinfo failed: Name d"es not resolve
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: " #0 /var/www/core/Redis.php(39): admin\core\Redis->connect(NULL, '6379', '0', '2.5')"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "#1 /var/www/core/Container.php(93): admin\core\Redis->__construct(Array)"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "#2 /var/www/core/Container.php(115): admin\core\Container::admin\core\{closure}()"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "#3 /var/www/models/Dashboard.php(334): admin\core\Container::getService('redisReader')"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "#4 /var/www/controllers/Dashboard.php(139): admin\models\Dashboard->getLoggedUserCount()"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: "#5 /var/www/index.php(49): admin\controllers\Dashboard->onlineUsersCount(Array)"
[24-Jul-2019 12:04:54] WARNING: [pool www] child 116 said into stdout: " EXCPT_END"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "WARN_START: /var/www/core/Redis.php:57  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve WARN_END"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "EXCPT_START: /var/www/core/Redis.php:61  Redis connection failed php_network_getaddresses: getaddrinfo failed: Name d"es not resolve
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: " #0 /var/www/core/Redis.php(39): admin\core\Redis->connect(NULL, '6379', '0', '2.5')"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "#1 /var/www/core/Container.php(93): admin\core\Redis->__construct(Array)"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "#2 /var/www/core/Container.php(115): admin\core\Container::admin\core\{closure}()"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "#3 /var/www/models/Dashboard.php(334): admin\core\Container::getService('redisReader')"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "#4 /var/www/controllers/Dashboard.php(139): admin\models\Dashboard->getLoggedUserCount()"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: "#5 /var/www/index.php(49): admin\controllers\Dashboard->onlineUsersCount(Array)"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 112 said into stdout: " EXCPT_END"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "WARN_START: /var/www/core/Redis.php:57  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve WARN_END"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "EXCPT_START: /var/www/core/Redis.php:61  Redis connection failed php_network_getaddresses: getaddrinfo failed: Name d"es not resolve
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: " #0 /var/www/core/Redis.php(39): admin\core\Redis->connect(NULL, '6379', '0', '2.5')"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "#1 /var/www/core/Container.php(93): admin\core\Redis->__construct(Array)"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "#2 /var/www/core/Container.php(115): admin\core\Container::admin\core\{closure}()"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "#3 /var/www/models/Dashboard.php(334): admin\core\Container::getService('redisReader')"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "#4 /var/www/controllers/Dashboard.php(139): admin\models\Dashboard->getLoggedUserCount()"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: "#5 /var/www/index.php(49): admin\controllers\Dashboard->onlineUsersCount(Array)"
[24-Jul-2019 12:04:55] WARNING: [pool www] child 116 said into stdout: " EXCPT_END"
```
I use the following configuration for this:
```
    <source>
      @type tail
      format multiline
      format_firstline /^\[(?<k8s_time_local>[^\]]*)\]\s[A-Z]{0,}:\s\[.*EXCPT_START:\s/
      format1 /^\[(?<k8s_time_local>[^\]]*)\]\s[A-Z]{0,}:\s\[.*EXCPT_START:\s(?<stack_log>.*)/
      # time_format %e-%b-%Y::%H:%M:%S
      read_from_head true
      path /var/log/containers/admin-*.log
      pos_file /var/log/admin.log.pos
      tag stack_trace.*
    </source>
```
The problem is that it captures the log correctly **ONLY** when those lines are saved in a text file at ` /var/log/containers/admin-<random characters>.log`. I did that for testing purpose. That said it is not capturing the realtime logs - that is the one that are coming out of pod.. 

I suspect this behavior is because when coming out of pod in the realtime, it comes line by line and when saved the lines in a file at the same location, it is a single write. Since it is a single write, the fluentd parser parses it at once.

@repeatedly, could you please help me sort this out. 

Thank you,
Arun V

**Comment by cosmo0920** [comment]
This should be handled by [fluent-plugin-detect-exceptions](https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions#top) in your pipeline.
