### ISSUE TITLE
Bump prometheus plugin version

### ISSUE THREAD

**Issue by geofffranks** [fluent/fluentd-kubernetes-daemonset#361]
Running into an issue with the latest image for v1-debian-cloudwatch, when using prometheus:

```
error_class=ArgumentError error="wrong number of arguments (given 2, expected 1; required keyword: docstring
```

Looks to be solved by https://github.com/fluent/fluent-plugin-prometheus/pull/121 in what i presume is fluentd-plugin-prometheus v1.6.1. Can the plugin version be bumped on these docker images? Looking into a PR for it, but I'm new to this repo, so it may not be a quick one.

**Comment by masterkain** [comment]
I have the same issue

```
2019-10-26T08:21:08.197433812Z 2019-10-26 08:21:08 +0000 [error]: #0 unexpected error error_class=ArgumentError error="wrong number of arguments (given 2, expected 1; required keyword: docstring)"
2019-10-26T08:21:08.197514624Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/prometheus-client-0.10.0/lib/prometheus/client/registry.rb:56:in `gauge'
2019-10-26T08:21:08.197523567Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-prometheus-1.5.0/lib/fluent/plugin/in_prometheus_output_monitor.rb:67:in `start'
2019-10-26T08:21:08.197526401Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/compat/call_super_mixin.rb:42:in `start'
2019-10-26T08:21:08.197528736Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:203:in `block in start'
2019-10-26T08:21:08.197531185Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
2019-10-26T08:21:08.197534106Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:191:in `each'
2019-10-26T08:21:08.197538043Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:191:in `block in lifecycle'
2019-10-26T08:21:08.197541509Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:178:in `each'
2019-10-26T08:21:08.197545481Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:178:in `lifecycle'
2019-10-26T08:21:08.197549225Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:202:in `start'
2019-10-26T08:21:08.197558349Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/engine.rb:274:in `start'
2019-10-26T08:21:08.197561909Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/engine.rb:219:in `run'
2019-10-26T08:21:08.197594087Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:808:in `run_engine'
2019-10-26T08:21:08.197598251Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:551:in `block in run_worker'
2019-10-26T08:21:08.197601587Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:733:in `main_process'
2019-10-26T08:21:08.197604904Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:546:in `run_worker'
2019-10-26T08:21:08.197608357Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
2019-10-26T08:21:08.197612299Z   2019-10-26 08:21:08 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-10-26T08:21:08.197615394Z   2019-10-26 08:21:08 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-10-26T08:21:08.197618429Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.3/bin/fluentd:8:in `<top (required)>'
2019-10-26T08:21:08.197621431Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
2019-10-26T08:21:08.197624309Z   2019-10-26 08:21:08 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
```
