### ISSUE TITLE
CrashLoopBackOff with error reading from socket: Could not parse data

### ISSUE THREAD

**Issue by alexdyas** [fluent/fluentd-kubernetes-daemonset#393]
Fluentd running on 3 K8s minions, writing to an Elastic instance. Basic functionality is working, I'm getting data into Elastic. However the Fluentd pods crash every 10-15 minutes with the following error:

```
...
2020-01-09 15:16:16 +0000 [info]: #0 fluentd worker is now running worker=0
2020-01-09 15:16:46 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:17:24 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:17:57 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:18:29 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:19:07 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:19:42 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:20:13 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2020-01-09 15:20:44 +0000 [info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 2, pod_cache_size: 5, pod_cache_watch_misses: 3, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
#<Thread:0x00007f0a521548d0@/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:265 run> terminated with exception (report_on_exception is true):
/fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/parser.rb:31:in `add': error reading from socket: Could not parse data (HTTP::ConnectionError)
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/connection.rb:214:in `read_more'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/connection.rb:92:in `readpartial'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/body.rb:30:in `readpartial'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/body.rb:36:in `each'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:265:in `block in configure'
/fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/parser.rb:31:in `add': Could not parse data (IOError)
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/connection.rb:214:in `read_more'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/connection.rb:92:in `readpartial'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/body.rb:30:in `readpartial'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/body.rb:36:in `each'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:265:in `block in configure'
Unexpected error error reading from socket: Could not parse data
  /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/parser.rb:31:in `add'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/connection.rb:214:in `read_more'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/connection.rb:92:in `readpartial'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/body.rb:30:in `readpartial'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/http-4.2.0/lib/http/response/body.rb:36:in `each'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:265:in `block in configure'
```

I don't see anything relevant in the Elastic logs.
Container image: `fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch`
Kubernetes v1.14.8.

Any help/pointers much appreciated.

**Comment by crain** [comment]
I am having the exact same issue.
Container image: fluent/fluentd-kubernetes-daemonset:v1.8.1-debian-elasticsearch7-1.0
Kubernetes: v1.14.10.

The DaemonSet is running with a serviceAccount assigned to the following ClusterRole:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd-logging
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
```

**Comment by alexdyas** [comment]
My ClusterRole differs only in the apiVersion, and that I have it in a distinct namespace:
```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: elastic-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
```
I tried putting Fluentd in the kube-system namespace but I get the same problem.

My hunch is that Fluentd doesn't have adequate access to the Kube api, but just a guess.

**Comment by ant1eicher** [comment]
I ran into this same issue on the latest version (2.4.1) of `fluent-plugin-kubernetes_metadata_filter`.

I don't think it's an auth issue, as the plugin is able to initialise a `kubeclient` instance and read from the Kubernetes API. This issue happens later when the namespace watcher receives a response on its stream that it can't parse:

In `kubernetes_metadata_watch_namespaces.rb`:
```
watcher = @client.watch_namespaces(resource_version)
...
watcher.each do |notice|
... <== this is where the exception gets triggered
```

I've disabled the watchers in my config, using `watch false`, and it's now stable. I think the watcher threads are used to update the pod and namespace metadata caches, so disabling them will result in a slight performance impact when metadata changes and there are cache misses (e.g. when a new pod launches). If there's a cache miss, the plugin will still go and find the correct metadata, it just takes a little longer. In our case, this doesn't happen often, so I don't think it matters much.

**Comment by alexdyas** [comment]
I ended up using Filebeat instead which worked out of the box. Soz.

**Comment by colltoaction** [comment]
My pods crash without the `watch false` setting too, but I haven't seen that stack trace in the logs. Did you do configure anything to see that output?

By the way, thanks for the workaround!

**Comment by ant1eicher** [comment]
Pleasure, Martín. No, that's not a stack trace, it's an excerpt from the plugin source code that I pasted.
