### ISSUE TITLE
v1-debian-kafka image give errors

### ISSUE THREAD

**Issue by fangwei18** [fluent/fluentd-kubernetes-daemonset#443]
```
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compression.rb:26:in `fetch'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compression.rb:26:in `find_codec'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compressor.rb:28:in `initialize'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/client.rb:260:in `new'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/client.rb:260:in `producer'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:242:in `block in get_producer'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:239:in `synchronize'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:239:in `get_producer'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:297:in `write'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/compat/output.rb:131:in `write'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:1133:in `try_flush'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-05-28 04:53:59 +0000 [info]: #0 [out_kafka] initialized kafka producer: kafka
2020-05-28 04:53:59 +0000 [warn]: #0 [out_kafka] failed to flush the buffer. retry_time=3 next_retry_seconds=2020-05-28 04:54:02 +0000 chunk="5a6ae1abbf1f7187d9f7fc04bf2501f4" error_class=RuntimeError error="Unknown compression codec "
  2020-05-28 04:53:59 +0000 [warn]: #0 suppressed same stacktrace
2020-05-28 04:54:02 +0000 [warn]: #0 [out_kafka] Send exception occurred: Unknown compression codec
2020-05-28 04:54:02 +0000 [warn]: #0 [out_kafka] Exception Backtrace : /fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compression.rb:27:in `block in find_codec'
```

kafka version: 2.12_2.5.0
image tag: fluent/fluentd-kubernetes-daemonset:v1-debian-kafka

I set FLUENT_KAFKA_BROKERS to kafka ip:port and FLUENT_KAFKA_DEFAULT_TOPIC to a created topic.

**Comment by fangwei18** [comment]
```
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compression.rb:26:in `fetch'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compression.rb:26:in `find_codec'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compressor.rb:28:in `initialize'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/client.rb:260:in `new'
/fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/client.rb:260:in `producer'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:242:in `block in get_producer'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:239:in `synchronize'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:239:in `get_producer'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka_buffered.rb:297:in `write'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/compat/output.rb:131:in `write'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:1133:in `try_flush'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-05-28 04:53:59 +0000 [info]: #0 [out_kafka] initialized kafka producer: kafka
2020-05-28 04:53:59 +0000 [warn]: #0 [out_kafka] failed to flush the buffer. retry_time=3 next_retry_seconds=2020-05-28 04:54:02 +0000 chunk="5a6ae1abbf1f7187d9f7fc04bf2501f4" error_class=RuntimeError error="Unknown compression codec "
  2020-05-28 04:53:59 +0000 [warn]: #0 suppressed same stacktrace
2020-05-28 04:54:02 +0000 [warn]: #0 [out_kafka] Send exception occurred: Unknown compression codec
2020-05-28 04:54:02 +0000 [warn]: #0 [out_kafka] Exception Backtrace : /fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/compression.rb:27:in `block in find_codec'
```

kafka version: 2.12_2.5.0
image tag: fluent/fluentd-kubernetes-daemonset:v1-debian-kafka

I set FLUENT_KAFKA_BROKERS to kafka ip:port and FLUENT_KAFKA_DEFAULT_TOPIC to a created topic.

**Comment by fangwei18** [comment]
after add 
```
          - name: FLUENT_KAFKA_REQUIRED_ACKS
            value: "-1"
          - name: FLUENT_KAFKA_COMPRESSION_CODEC
            value: "gzip"
          - name: FLUENT_KAFKA_MAX_SEND_LIMIT_BYTES
            value: "1000000"    
          - name: FLUENT_UID
            value: "0"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"  
```
