### ISSUE TITLE
Getting fluentd pod [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:249:in `configure' while exporting Kubernetes Logs to Elasticsearch Using Fluentd 

### ISSUE THREAD

**Issue by anilsakr** [fluent/fluentd-kubernetes-daemonset#483]
I configure the EFK stack to my kuberenetes and configured the cognite when I try to push the application pod logs to Kibana by using the fluentd getting the error

2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:249:in `configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/plugin.rb:164:in `configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:130:in `add_match'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:72:in `block in configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:64:in `each'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:64:in `configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:150:in `configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:131:in `configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:96:in `run_configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:801:in `run_configure'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:548:in `block in run_worker'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:730:in `main_process'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:544:in `run_worker'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2020-07-31 06:26:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2020-07-31 06:26:58 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.4.2/bin/fluentd:8:in `<top (required)>'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
  2020-07-31 06:26:58 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
2020-07-31 06:26:58 +0000 [info]: Worker 0 finished unexpectedly with status 1
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-concat' version '2.3.0'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.4.3'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.5.1'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-json-in-json-2' version '1.0.2'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.3.0'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2020-07-31 06:26:59 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-07-31 06:26:59 +0000 [info]: gem 'fluentd' version '1.4.2'
2020-07-31 06:26:59 +0000 [info]: adding match pattern="fluent.**" type="null"
2020-07-31 06:26:59 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2020-07-31 06:26:59 +0000 [info]: adding match pattern="**" type="elasticsearch"
2020-07-31 06:26:59 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
[fluentdlog.txt](https://github.com/fluent/fluentd-kubernetes-daemonset/files/5005744/fluentdlog.txt)
[es-proxy-log.txt](https://github.com/fluent/fluentd-kubernetes-daemonset/files/5005755/es-proxy-log.txt)

**Comment by cosmo0920** [comment]
Your using Fluentd Elasticsearch image is a bit of old.
Could you use the latest `v1.11-debian-elasticsearch7-1` image or `v1.11-debian-elasticsearch6-1` image?
