### ISSUE TITLE
Starting fluentd worker crashes with -- [error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::NewTailInput::DEFAULT_FILE_PERMISSION

### ISSUE THREAD

**Issue by LudwigTirazona** [fluent/fluentd-kubernetes-daemonset#99]
Dockerfile:

https://pastebin.com/Ny69sWYp

Log output:

https://pastebin.com/UPa8qZTi

What needs to be done to get this to run?

**Comment by calinah** [comment]
I'm also getting the same error:

```
[error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::NewTailInput::DEFAULT_FILE_PERMISSION\nDid you mean?  Fluent::DEFAULT_OJ_OPTIONS"
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/plugin/in_tail.rb:129:in `start'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:165:in `block in start'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `each'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `each'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:164:in `start'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:274:in `start'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:219:in `run'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:699:in `main_process'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-05-16 09:43:28 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-05-16 09:43:28 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-05-16 09:43:28 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
  2018-05-16 09:43:28 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `load'
  2018-05-16 09:43:28 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
```
Worth mentioning that this has been working up until a few days ago. Looking at the image I can see a commit "Apply oj changes" https://github.com/fluent/fluentd-kubernetes-daemonset/commit/3408f63cf62a10fbfb51d54769acf7aff0372f9c - could this be what's causing the error?
We're using the `fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch` image
@edsiper , @repeatedly  can you please advise?

**Comment by repeatedly** [comment]
>  could this be what's causing the error?

This is not related.
The problem is your environment mixes fluentd v0.12 and fluentd v1.x.
I'm not sure the root cause but your image depend on older broken images.

**Comment by calinah** [comment]
@repeatedly thanks for responding :) - yes I can see that is the case. Although I'm not specifying anywhere to install fluentd v1.0.2 it is installed based on another dependency. I'll look into this further and once fixed I'll update my findings.

**Comment by Stelminator** [comment]
@calinah you might just need to update.

https://github.com/fluent/fluentd-kubernetes-daemonset/issues/69
https://github.com/fluent/fluentd-kubernetes-daemonset/pull/70

**Comment by cosmo0920** [comment]
fluent-plugin-logzio seems one of the culprit to bump Fluentd version to v1 from 0.12.
Non-specified version installation is dangerous.
You should use fluent-plugin-logzio v0.0.14 for Fluentd v0.12 but this version of Fluentd is already EOL.
The newer Fluentd v1 series and new docker images solve this issue.
This issue should be closed.
